# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QPushButton, QSizePolicy, QTextEdit,
    QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.setWindowModality(Qt.WindowModality.NonModal)
        Widget.resize(800, 644)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        self.bottoneOk = QPushButton(Widget)
        self.bottoneOk.setObjectName(u"bottoneOk")
        self.bottoneOk.setGeometry(QRect(650, 10, 41, 41))
        self.textInput = QTextEdit(Widget)
        self.textInput.setObjectName(u"textInput")
        self.textInput.setGeometry(QRect(20, 10, 621, 41))
        self.bottoneCanc = QPushButton(Widget)
        self.bottoneCanc.setObjectName(u"bottoneCanc")
        self.bottoneCanc.setGeometry(QRect(700, 10, 41, 41))
        self.bottoneBoh = QPushButton(Widget)
        self.bottoneBoh.setObjectName(u"bottoneBoh")
        self.bottoneBoh.setGeometry(QRect(750, 10, 41, 41))
        self.textOutput = QTextEdit(Widget)
        self.textOutput.setObjectName(u"textOutput")
        self.textOutput.setGeometry(QRect(20, 70, 611, 391))
        self.textOutput.setReadOnly(True)
        self.line = QFrame(Widget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(20, 50, 771, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.bottone1 = QPushButton(Widget)
        self.bottone1.setObjectName(u"bottone1")
        self.bottone1.setGeometry(QRect(640, 370, 41, 41))
        self.bottone3 = QPushButton(Widget)
        self.bottone3.setObjectName(u"bottone3")
        self.bottone3.setGeometry(QRect(750, 370, 41, 41))
        self.bottone2 = QPushButton(Widget)
        self.bottone2.setObjectName(u"bottone2")
        self.bottone2.setGeometry(QRect(695, 370, 41, 41))
        self.bottone5 = QPushButton(Widget)
        self.bottone5.setObjectName(u"bottone5")
        self.bottone5.setGeometry(QRect(695, 320, 41, 41))
        self.bottone6 = QPushButton(Widget)
        self.bottone6.setObjectName(u"bottone6")
        self.bottone6.setGeometry(QRect(750, 320, 41, 41))
        self.bottone4 = QPushButton(Widget)
        self.bottone4.setObjectName(u"bottone4")
        self.bottone4.setGeometry(QRect(640, 320, 41, 41))
        self.bottone8 = QPushButton(Widget)
        self.bottone8.setObjectName(u"bottone8")
        self.bottone8.setGeometry(QRect(695, 270, 41, 41))
        self.bottone9 = QPushButton(Widget)
        self.bottone9.setObjectName(u"bottone9")
        self.bottone9.setGeometry(QRect(750, 270, 41, 41))
        self.bottone7 = QPushButton(Widget)
        self.bottone7.setObjectName(u"bottone7")
        self.bottone7.setGeometry(QRect(640, 270, 41, 41))
        self.bottoneper = QPushButton(Widget)
        self.bottoneper.setObjectName(u"bottoneper")
        self.bottoneper.setGeometry(QRect(720, 230, 31, 31))
        self.bottonediviso = QPushButton(Widget)
        self.bottonediviso.setObjectName(u"bottonediviso")
        self.bottonediviso.setGeometry(QRect(760, 230, 31, 31))
        self.bottonemeno = QPushButton(Widget)
        self.bottonemeno.setObjectName(u"bottonemeno")
        self.bottonemeno.setGeometry(QRect(680, 230, 31, 31))
        self.bottoneUguale = QPushButton(Widget)
        self.bottoneUguale.setObjectName(u"bottoneUguale")
        self.bottoneUguale.setGeometry(QRect(750, 420, 41, 41))
        self.bottonepiu = QPushButton(Widget)
        self.bottonepiu.setObjectName(u"bottonepiu")
        self.bottonepiu.setGeometry(QRect(640, 230, 31, 31))
        self.bottone0 = QPushButton(Widget)
        self.bottone0.setObjectName(u"bottone0")
        self.bottone0.setGeometry(QRect(640, 420, 51, 41))
        self.line_2 = QFrame(Widget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(20, 460, 771, 16))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.bottoneTondaAperta = QPushButton(Widget)
        self.bottoneTondaAperta.setObjectName(u"bottoneTondaAperta")
        self.bottoneTondaAperta.setGeometry(QRect(640, 190, 31, 31))
        self.bottoneTondaChiusa = QPushButton(Widget)
        self.bottoneTondaChiusa.setObjectName(u"bottoneTondaChiusa")
        self.bottoneTondaChiusa.setGeometry(QRect(680, 190, 31, 31))
        self.frame = QFrame(Widget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(689, 70, 101, 81))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 49, 16))
        self.checkBoxFrazioni = QCheckBox(self.frame)
        self.checkBoxFrazioni.setObjectName(u"checkBoxFrazioni")
        self.checkBoxFrazioni.setGeometry(QRect(20, 60, 75, 20))
        self.checkBoxInteri = QCheckBox(self.frame)
        self.checkBoxInteri.setObjectName(u"checkBoxInteri")
        self.checkBoxInteri.setGeometry(QRect(20, 20, 75, 20))
        self.checkBoxInteri.setChecked(False)
        self.checkBoxFloat = QCheckBox(self.frame)
        self.checkBoxFloat.setObjectName(u"checkBoxFloat")
        self.checkBoxFloat.setGeometry(QRect(20, 40, 75, 20))
        self.checkBoxFloat.setChecked(False)
        self.bottonePunto = QPushButton(Widget)
        self.bottonePunto.setObjectName(u"bottonePunto")
        self.bottonePunto.setGeometry(QRect(700, 420, 41, 41))
        self.comboBox = QComboBox(Widget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(720, 190, 72, 31))
        self.comboBoxMemoria = QComboBox(Widget)
        self.comboBoxMemoria.setObjectName(u"comboBoxMemoria")
        self.comboBoxMemoria.setGeometry(QRect(640, 90, 41, 25))
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(640, 70, 54, 17))
        self.bottoneSvuotaMemoria = QPushButton(Widget)
        self.bottoneSvuotaMemoria.setObjectName(u"bottoneSvuotaMemoria")
        self.bottoneSvuotaMemoria.setGeometry(QRect(640, 120, 41, 31))
        font = QFont()
        font.setFamilies([u"Sans Serif"])
        font.setPointSize(6)
        self.bottoneSvuotaMemoria.setFont(font)
        self.bottoneCE = QPushButton(Widget)
        self.bottoneCE.setObjectName(u"bottoneCE")
        self.bottoneCE.setGeometry(QRect(660, 160, 21, 21))
        font1 = QFont()
        font1.setPointSize(7)
        self.bottoneCE.setFont(font1)
        self.bottoneC = QPushButton(Widget)
        self.bottoneC.setObjectName(u"bottoneC")
        self.bottoneC.setGeometry(QRect(640, 160, 21, 21))
        self.bottoneC.setFont(font1)
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 470, 171, 17))
        self.textUM1 = QTextEdit(Widget)
        self.textUM1.setObjectName(u"textUM1")
        self.textUM1.setGeometry(QRect(40, 490, 151, 31))
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 490, 16, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.label_4.setFont(font2)
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(200, 490, 16, 31))
        self.label_5.setFont(font2)
        self.textUM2 = QTextEdit(Widget)
        self.textUM2.setObjectName(u"textUM2")
        self.textUM2.setGeometry(QRect(330, 490, 151, 31))
        self.textFC = QTextEdit(Widget)
        self.textFC.setObjectName(u"textFC")
        self.textFC.setGeometry(QRect(220, 490, 111, 31))
        self.comboBoxConversioni = QComboBox(Widget)
        self.comboBoxConversioni.setObjectName(u"comboBoxConversioni")
        self.comboBoxConversioni.setGeometry(QRect(561, 490, 181, 31))
        self.line_3 = QFrame(Widget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 520, 771, 16))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.pushButtonConversioni = QPushButton(Widget)
        self.pushButtonConversioni.setObjectName(u"pushButtonConversioni")
        self.pushButtonConversioni.setGeometry(QRect(480, 490, 51, 31))
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(630, 470, 71, 17))
        self.pushButtonConversioniRimuovi = QPushButton(Widget)
        self.pushButtonConversioniRimuovi.setObjectName(u"pushButtonConversioniRimuovi")
        self.pushButtonConversioniRimuovi.setGeometry(QRect(740, 490, 51, 31))
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(500, 530, 301, 111))
        self.label_7.setTextFormat(Qt.TextFormat.AutoText)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Calcolatrice Peppinica", None))
        self.bottoneOk.setText(QCoreApplication.translate("Widget", u"Go", None))
        self.bottoneCanc.setText(QCoreApplication.translate("Widget", u"C", None))
        self.bottoneBoh.setText(QCoreApplication.translate("Widget", u"?", None))
        self.bottone1.setText(QCoreApplication.translate("Widget", u"1", None))
        self.bottone3.setText(QCoreApplication.translate("Widget", u"3", None))
        self.bottone2.setText(QCoreApplication.translate("Widget", u"2", None))
        self.bottone5.setText(QCoreApplication.translate("Widget", u"5", None))
        self.bottone6.setText(QCoreApplication.translate("Widget", u"6", None))
        self.bottone4.setText(QCoreApplication.translate("Widget", u"4", None))
        self.bottone8.setText(QCoreApplication.translate("Widget", u"8", None))
        self.bottone9.setText(QCoreApplication.translate("Widget", u"9", None))
        self.bottone7.setText(QCoreApplication.translate("Widget", u"7", None))
        self.bottoneper.setText(QCoreApplication.translate("Widget", u"*", None))
        self.bottonediviso.setText(QCoreApplication.translate("Widget", u"/", None))
        self.bottonemeno.setText(QCoreApplication.translate("Widget", u"-", None))
        self.bottoneUguale.setText(QCoreApplication.translate("Widget", u"=", None))
        self.bottonepiu.setText(QCoreApplication.translate("Widget", u"+", None))
        self.bottone0.setText(QCoreApplication.translate("Widget", u"0", None))
        self.bottoneTondaAperta.setText(QCoreApplication.translate("Widget", u"(", None))
        self.bottoneTondaChiusa.setText(QCoreApplication.translate("Widget", u")", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Rileva:", None))
        self.checkBoxFrazioni.setText(QCoreApplication.translate("Widget", u"Frazioni", None))
        self.checkBoxInteri.setText(QCoreApplication.translate("Widget", u"Interi", None))
        self.checkBoxFloat.setText(QCoreApplication.translate("Widget", u"Float", None))
        self.bottonePunto.setText(QCoreApplication.translate("Widget", u".", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Mem.", None))
        self.bottoneSvuotaMemoria.setText(QCoreApplication.translate("Widget", u"Svuota\n"
"Memoria", None))
        self.bottoneCE.setText(QCoreApplication.translate("Widget", u"CE", None))
        self.bottoneC.setText(QCoreApplication.translate("Widget", u"C", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"Crea / modifica conversione", None))
#if QT_CONFIG(accessibility)
        self.textUM1.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.textUM1.setDocumentTitle("")
        self.label_4.setText(QCoreApplication.translate("Widget", u"1", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"=", None))
        self.pushButtonConversioni.setText(QCoreApplication.translate("Widget", u"Salva", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Salvati:", None))
        self.pushButtonConversioniRimuovi.setText(QCoreApplication.translate("Widget", u"Rimuovi", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">Calcolatrice Peppinica</span><br/><span style=\" color:#3e3e3e;\">by </span><span style=\" font-style:italic;\">Valenzisi Peppino </span><span style=\" color:#c3594b;\">(</span>\u2310\u25a0<span style=\" color:#c3594b;\">_</span>\u25a0<span style=\" color:#c3594b;\">)</span><br/><br/>Per richieste di nuove funzionalit\u00e0<br/>o segnalazione bug scrivi un messaggio su<br/>https://peppinosolutions.wordpress.com/contatto/</p></body></html>", None))
    # retranslateUi

